addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.0.0")
addSbtPlugin("com.github.gseitz" % "sbt-release" % "1.0.11")
addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.1.2")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "2.5")
addSbtPlugin("com.thoughtworks.sbt-api-mappings" % "sbt-api-mappings" % "3.0.0")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"               % "0.5.0")
addSbtPlugin("org.xerial.sbt"   % "sbt-sonatype"              % "3.9.2")
addSbtPlugin("com.jsuereth"     % "sbt-pgp"                   % "2.0.0-M2")
